# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up
# use this command to run production docker-compose
services:
  
  nginx:
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    ports:
      - 8080:80
      - 4443:443
    depends_on:
      - mysql
      - php
      - assets

  php:
    build:
      context: .
      dockerfile: php.prod.dockerfile

  assets:
    image: node:current-alpine
    volumes: 
      - ./src:/var/www/html
    command: ['/bin/sh', '-c', 'npm install && npm run production']
    working_dir: /var/www/html